name: tabib
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.5
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  shared_preferences: ^2.5.3
  pdf: ^3.10.4
  printing: ^5.12.0
  intl: ^0.20.2
  awesome_dialog: ^3.1.0
  path_provider: ^2.1.2
  open_file: ^3.5.4
  device_preview: ^1.3.1
  google_sign_in: ^6.1.5

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
