// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpUmDbByW1i47fMiF4Kb9A3JSsraY_6UA',
    appId: '1:780410177377:web:955d14e09c0ca330fd2720',
    messagingSenderId: '780410177377',
    projectId: 'tabib-d9f36',
    authDomain: 'tabib-d9f36.firebaseapp.com',
    storageBucket: 'tabib-d9f36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO8Qj_rrSsAJ_ltg2QNzeQp8FWA01hns4',
    appId: '1:780410177377:android:ce427ca50d3457d4fd2720',
    messagingSenderId: '780410177377',
    projectId: 'tabib-d9f36',
    storageBucket: 'tabib-d9f36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQl_utEgggkWagMXUgYaxVroo6yc35Y4',
    appId: '1:780410177377:ios:a2d6d8e2253ed538fd2720',
    messagingSenderId: '780410177377',
    projectId: 'tabib-d9f36',
    storageBucket: 'tabib-d9f36.firebasestorage.app',
    iosBundleId: 'com.example.tabib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQl_utEgggkWagMXUgYaxVroo6yc35Y4',
    appId: '1:780410177377:ios:a2d6d8e2253ed538fd2720',
    messagingSenderId: '780410177377',
    projectId: 'tabib-d9f36',
    storageBucket: 'tabib-d9f36.firebasestorage.app',
    iosBundleId: 'com.example.tabib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpUmDbByW1i47fMiF4Kb9A3JSsraY_6UA',
    appId: '1:780410177377:web:09fd91bf2a263714fd2720',
    messagingSenderId: '780410177377',
    projectId: 'tabib-d9f36',
    authDomain: 'tabib-d9f36.firebaseapp.com',
    storageBucket: 'tabib-d9f36.firebasestorage.app',
  );
}
